### ISSUE TITLE
Want to contribute but not sure how.

### ISSUE THREAD

**Issue by maxwell-bland** [palafucker/palafucker.github.io#1]
Palafucker, listen, let me in on this ####. 

I understand I just need to get good.

But I am having a hard time understanding the files; it is like, a code, I think?

**Comment by CreaturePhil** [comment]
It is not Pala. It is Palafucker. I'm not the Palafucker. The Palafucker is the Palafucker.

This is not the source code. This is just the output generated by [Gatsby.js](https://www.gatsbyjs.org/). I was just trying it out to see how Gatsby implemented the [PRPL pattern](https://developers.google.com/web/fundamentals/performance/prpl-pattern/).

**Comment by maxwell-bland** [comment]
This is v tasty, thanks for the insight. 

I'm considering this issue resolved.
